spring.application.name=loginAPI
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=aloneking
spring.datasource.password=@loneking07
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
